import os
import json
import argparse
from googleapiclient.discovery import build
from langchain_core.tools import tool
from dotenv import load_dotenv
import logging

from logger_config import setup_logging

setup_logging()
logger = logging.getLogger(__name__)

# --- START OF SETUP ---
# Load environment variables from a .env file
logger.info("Loading environment variables")
load_dotenv()

# This code tells LangChain to use the keys you just pasted
# Ensure your .env file has GOOGLE_API_KEY="your_key_here"
# --- END OF SETUP ---


# --- The Search Tool ---

@tool
def google_search(search_query: str) -> str:
    """
    Performs a Google search using the Custom Search JSON API and returns 
    the top 5 results as a JSON string.
    
    Args:
        search_query: The string to search for, generated by the Searcher Agent.
        
    Returns:
        A JSON string containing a list of search results, each with a
        title, link, and snippet. Returns an error message if the search fails.
    """
    logger.info(f"--- Executing Search Tool with query: {search_query} ---")
    
    # Get API keys from environment variables
    API_KEY = os.getenv("GOOGLE_SEARCH_API_KEY")
    CSE_ID = os.getenv("GOOGLE_CSE_ID")

    if not API_KEY or not CSE_ID:
        logger.error("Missing GOOGLE_SEARCH_API_KEY or GOOGLE_CSE_ID environment variables.")
        return json.dumps({
            "error": "Missing GOOGLE_SEARCH_API_KEY or GOOGLE_CSE_ID environment variables."
        })

    try:
        # Build the search service
        logger.info("Building Google Search service")
        service = build("customsearch", "v1", developerKey=API_KEY)
        
        # Execute the search request for top 5 results
        logger.info(f"Executing search for query: {search_query}")
        result = service.cse().list(
            q=search_query,
            cx=CSE_ID,
            num=5  # Request top 5 results
        ).execute()

        # --- Parse the results ---
        search_items = result.get('items', [])
        
        if not search_items:
            logger.warning("No results found for this query.")
            return json.dumps({"message": "No results found for this query."})

        # Format the results into a clean list of dictionaries
        formatted_results = []
        for item in search_items:
            formatted_results.append({
                "title": item.get('title'),
                "snippet": item.get('snippet'),
                "link": item.get('link')
            })
        
        # Return the list as a JSON string
        logger.info("Search successful, returning formatted results.")
        return json.dumps(formatted_results)

    except Exception as e:
        logger.error(f"Error during Google Search: {e}", exc_info=True)
        return json.dumps({
            "error": f"An error occurred during the search: {str(e)}"
        })

if __name__ == "__main__":
    # This allows you to run the script directly from the command line
    # to test the google_search tool.
    # Example: python -m backend.tools.google_search "travel to Peru"
    parser = argparse.ArgumentParser(description="Test the Google Search tool.")
    parser.add_argument("query", type=str, help="The search query to test.")
    args = parser.parse_args()

    # Invoke the tool
    results_json = google_search.invoke(args.query)
    
    # Pretty-print the JSON results
    results = json.loads(results_json)
    logger.info(json.dumps(results, indent=2))